### ISSUE TITLE
xrange unsupported in python3

### ISSUE THREAD

**Issue by pheintzman** [svohr/mixemt#22]
Hi Sam,

I got an error using mixemt v0.2 (current version as of 20200727) in python3.
On line 236, xrange is used, but this is not supported in python3.

This issue is resolved by replacing:
    for i in xrange(len(reads)):

with:
    for i in range(len(reads)):

Best,
Pete

**Comment by svohr** [comment]
Hi Pete,

Sorry I just noticed your issue. Thanks for pointing out the error. I added your fix to the main branch and I hope it didn't cause you too much trouble.

Sam
